[package]
name = "jpg_to_webp_coder"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.19.0"
egui = "0.19.0"
egui_extras = "0.19.0"
image = "0.24.6"
webp = "0.2.2"
rayon = "1.5.3"
rfd = "0.9.0"
parking_lot = "0.12.1"
chrono = "0.4"
sys-info = "0.9"

